INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxeEnhanced.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/RscRtDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SCHandlerRtDxe.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf
INF QcomPkg/Drivers/TzDxe/ScmDxeCompat.inf
INF QcomPkg/Drivers/TzDxe/TzDxeLA.inf
INF QcomPkg/Drivers/PsStateDxe/PsStateDxe.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
INF QcomPkg/Drivers/VendorLogfsDxe/VendorLogfsDxe.inf
INF QcomPkg/Drivers/CfgUtilDxe/CfgUtilDxe.inf
INF QcomPkg/Drivers/NubiaBoardDxe/NubiaBoardDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF QcomPkg/Drivers/FontDxe/FontDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/HSUartDxe/HSUartDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/QupDxe/QupDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
INF QcomPkg/Drivers/EDLoadDxe/EDLoadDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/UFSDxe/UFSDxe.inf
INF QcomPkg/Drivers/CmdDbDxe/CmdDbDxe.inf
INF QcomPkg/Drivers/PwrUtilsDxe/PwrUtilsDxe.inf
INF QcomPkg/Drivers/RpmhDxe/RpmhDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/MailboxDxe/MailboxDxe.inf
INF QcomPkg/Drivers/QcomScmiDxe/QcomScmiDxe.inf
INF QcomPkg/Drivers/CalibrationDxe/CalibrationDxe.inf
INF QcomPkg/Drivers/VcsDxe/VcsDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/ICBDxe/ICBDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/QcomBds/QcomBds.inf
INF QcomPkg/Application/QcomChargerApp/QcomChargerApp.inf
INF QcomPkg/Drivers/RscDxe/RscDxe.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
    SECTION UI = "BDS_Menu.cfg"
    SECTION RAW = RawFiles/BDS_Menu.cfg
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}

INF QcomPkg/Application/Ebl/Ebl.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF QcomPkg/Drivers/CPRDxe/CPRDxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/FeatureEnablerDxe/FeatureEnablerDxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/QRKSDxe/QRKSDxe.inf
INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
INF QcomPkg/Drivers/IPCCDxe/IPCCDxe.inf
INF QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
INF QcomPkg/Drivers/PmicGlinkDxe/PmicGlinkDxe.inf
INF QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLA.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/XhciPciEmulationDxe/XhciPciEmulationDxe.inf
INF QcomPkg/Drivers/XhciDxe/XhciDxe.inf
INF QcomPkg/Drivers/UsbBusDxe/UsbBusDxe.inf
INF QcomPkg/Drivers/UsbKbDxe/UsbKbDxe.inf
INF QcomPkg/Drivers/UsbMassStorageDxe/UsbMassStorageDxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/UsbInitDxe/UsbInitDxe.inf
INF QcomPkg/Drivers/UCDxe/UCDxe.inf
INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Drivers/PILProxyDxe/PILProxyDxe.inf
INF QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
INF QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
INF QcomPkg/Drivers/SPSSDxe/SPSSDxe.inf
INF QcomPkg/Drivers/FvUtilsDxe/FvUtilsEnhancedDxe.inf
INF QcomPkg/Drivers/RmVmDxe/RmVmDxe.inf
INF QcomPkg/Drivers/I2CHapticDxe/I2CHapticDxe.inf
INF QcomPkg/Drivers/ParserDxe/ParserEnhancedDxe.inf
INF QcomPkg/Drivers/SerialPortDxe/SerialPortDxe.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
    SECTION UI = "logo1.bmp"
    SECTION RAW = RawFiles/logo1.bmp
}


FILE FREEFORM = 8CAE2C55-FC5A-410B-812B-8CA22F572F36 {
    SECTION UI = "Panel_truly_wqxga_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dsc_cmd.xml
}


FILE FREEFORM = 13AC9DC9-0092-4374-AE1A-06FF35950FD0 {
    SECTION UI = "Panel_truly_wqxga_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dsc_vid.xml
}


FILE FREEFORM = FC6315F9-F8FE-4222-A1E3-226DF55D7592 {
    SECTION UI = "Panel_truly_wqxga_dual_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dual_cmd.xml
}


FILE FREEFORM = 95E7B040-26A2-4511-9ABB-1D95D6DA7082 {
    SECTION UI = "Panel_truly_wqxga_dual_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_dual_vid.xml
}


FILE FREEFORM = 8BC595B7-391A-4A9A-8256-5B9983B30392 {
    SECTION UI = "Panel_sharp_4k_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_4k_dsc_cmd.xml
}


FILE FREEFORM = 19B58ACD-B1F8-4078-B9A5-A33584B680E2 {
    SECTION UI = "Panel_sharp_4k_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sharp_4k_dsc_vid.xml
}


FILE FREEFORM = 0AE323D6-2EBE-11E8-8349-9BA636A0D80C {
    SECTION UI = "Panel_sharp_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_1080p_cmd.xml
}


FILE FREEFORM = 87273B42-311D-11E8-9324-DFB2DADFC3D1 {
    SECTION UI = "Panel_truly_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_1080p_cmd.xml
}


FILE FREEFORM = BAFD3200-311D-11E8-8651-0FB3CACF38FB {
    SECTION UI = "Panel_truly_1080p_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_1080p_vid.xml
}


FILE FREEFORM = 88CA5ABF-D0AC-4093-A68C-0CFAE1EF9635 {
    SECTION UI = "Panel_boe_amoled_wqhd_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wqhd_dsc_cmd.xml
}


FILE FREEFORM = 6523A5C9-91CB-45C0-A2DC-25997CF23369 {
    SECTION UI = "Panel_boe_amoled_wqhd_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_wqhd_dsc_vid.xml
}


FILE FREEFORM = D7170685-5965-4B44-9305-37CDB199B9BE {
    SECTION UI = "Panel_boe_amoled_fhd_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_boe_amoled_fhd_dsc_cmd.xml
}


FILE FREEFORM = 8F276EE4-E75E-4C3B-8BCC-C37771E26478 {
    SECTION UI = "Panel_nt36860_wqhd_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt36860_wqhd_dsc_cmd.xml
}


FILE FREEFORM = 6F2D4884-D8A0-11E9-AF7A-D77B1FE990EC {
    SECTION UI = "Panel_nt36860_wqhd_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_nt36860_wqhd_dsc_vid.xml
}


FILE FREEFORM = 81CE7295-491D-4E3F-AAA7-AB43FEF2F615 {
    SECTION UI = "Panel_r66451_60hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_r66451_60hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 8297C793-9861-422C-9F67-D447AF1EA812 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 61156380-EB8A-4618-940F-AB9BDEA1EEC2 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd_hdk.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd_hdk.xml
}


FILE FREEFORM = 44B09226-C2B4-45ED-AA6F-6686DB103978 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = D3F8580C-CCB8-4804-BB03-776E7B542FC2 {
    SECTION UI = "Panel_secondary_truly_1080p_cmd.xml"
    SECTION RAW = RawFiles/Panel_secondary_truly_1080p_cmd.xml
}


FILE FREEFORM = D192FEE9-6A04-4BE8-ABFE-5534E2B457EC {
    SECTION UI = "Panel_secondary_truly_1080p_vid.xml"
    SECTION RAW = RawFiles/Panel_secondary_truly_1080p_vid.xml
}


FILE FREEFORM = 9874B60A-6B80-4D76-8EEB-7862C780EC03 {
    SECTION UI = "Panel_r66451_144hz_fhd_plus_dsc_cmd_cphy.xml"
    SECTION RAW = RawFiles/Panel_r66451_144hz_fhd_plus_dsc_cmd_cphy.xml
}


FILE FREEFORM = BC28E12E-C7E0-47F9-BBF9-0B45ED6F4B18 {
    SECTION UI = "Panel_r66451_144hz_fhd_plus_dsc_vid_cphy.xml"
    SECTION RAW = RawFiles/Panel_r66451_144hz_fhd_plus_dsc_vid_cphy.xml
}


FILE FREEFORM = 637AD94D-7D9B-4D5F-B420-770B65BECDA8 {
    SECTION UI = "Panel_r66451_60hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_r66451_60hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = AE3F9548-010C-4AEC-A9D2-4AE3E16D2F8B {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 12372575-2A07-4C4E-BE92-6093A55FED33 {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = 36630E03-0236-4983-ABDE-F982B23419FE {
    SECTION UI = "Panel_vtdr6130_60hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_60hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 573FA171-1D5C-4C12-BDC8-19DCEFBBD483 {
    SECTION UI = "Panel_vtdr6130_60hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_60hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = 0A60AF27-D18D-452F-BB8B-1A886F7F6CCC {
    SECTION UI = "Panel_sharp_120hz_qhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sharp_120hz_qhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 81466938-BB9E-43DC-A208-A41BA82A5861 {
    SECTION UI = "Panel_sharp_120hz_qhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sharp_120hz_qhd_plus_dsc_vid.xml
}


FILE FREEFORM = 23EB5E2D-4A4D-4B35-BB7B-BE39D7EE440D {
    SECTION UI = "Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = A413F4E1-50FE-4848-82F1-EFB814608221 {
    SECTION UI = "Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_secondary_vtdr6130_144hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = EB0A97F6-39DB-41D4-9B3C-CA3BADC144B4 {
    SECTION UI = "Panel_truly_wqxga_cmd_splitlink.xml"
    SECTION RAW = RawFiles/Panel_truly_wqxga_cmd_splitlink.xml
}


FILE FREEFORM = F4A245C8-940E-4523-A53B-82E3C8BC6970 {
    SECTION UI = "Panel_r66451_120hz_fhd_plus_dsc_cmd_demura.xml"
    SECTION RAW = RawFiles/Panel_r66451_120hz_fhd_plus_dsc_cmd_demura.xml
}


FILE FREEFORM = 3DE03011-41E8-4353-A4E5-02721E71A0F4 {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_demura.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_demura.xml
}


FILE FREEFORM = 0EF4D970-0B59-4AF4-A8F7-F6A239EED792 {
    SECTION UI = "Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml
}


FILE FREEFORM = 95FA1AB2-A4C8-4891-ABD3-3DE4BAB07680 {
    SECTION UI = "Panel_rumi_cwb_vga_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_rumi_cwb_vga_dsc_vid.xml
}


FILE FREEFORM = 138816EF-44B3-4FA1-9F8C-CA23B0AC72CD {
    SECTION UI = "Panel_vtdr6130_120hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_120hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 54603FD1-6CD3-469E-A2FB-D0759525C423 {
    SECTION UI = "Panel_vtdr6130_120hz_fhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_vtdr6130_120hz_fhd_plus_dsc_vid.xml
}


FILE FREEFORM = 564F33FA-E572-4678-A575-AF6AC20ED2BD {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 939DFDDF-82A2-459D-9E28-A38719B059B5 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy.xml
}


FILE FREEFORM = 3D2431EB-AD6D-4753-B13C-26D4E7789A2E {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid.xml
}


FILE FREEFORM = 059BCC95-F398-411D-950D-02FD9F224755 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy.xml
}


FILE FREEFORM = 019F1D56-BF74-49A3-9918-0E8125E101D2 {
    SECTION UI = "Panel_sec_nt37801_120hz_wqhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_sec_nt37801_120hz_wqhd_plus_dsc_cmd.xml
}


FILE FREEFORM = 2615FB61-D05F-4C8F-A721-A2EECE2CB4C9 {
    SECTION UI = "Panel_nt37801_10bit_wqhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_nt37801_10bit_wqhd_plus_dsc_vid.xml
}


FILE FREEFORM = 109E1AFF-D049-4FB5-A072-C46B42EE19A2 {
    SECTION UI = "Panel_nt37801_10bit_wqhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt37801_10bit_wqhd_plus_dsc_cmd.xml
}


FILE FREEFORM = D8DFD1C2-CA91-4326-8523-80485AE1736B {
    SECTION UI = "Panel_nt37801_120hz_fhd_plus_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_fhd_plus_dsc_cmd.xml
}


FILE FREEFORM = FFC7B4C7-D596-4E18-BF65-69033EB1950C {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_spr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_spr.xml
}


FILE FREEFORM = F9E32994-8AF4-4EAC-A863-825DC36B978D {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_cphy_demura.xml
}


FILE FREEFORM = 3A712E44-C2A4-4D36-95AC-81B3A4505AA4 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_cphy_demura.xml
}


FILE FREEFORM = F2289587-6D5C-4B42-9596-87188499D6DF {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura.xml
}


FILE FREEFORM = 1B41CB60-08EB-45BE-9609-7C95A97D81F4 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura.xml
}


FILE FREEFORM = 2ECFB0AF-93AF-4A3B-B420-43D46F77DF54 {
    SECTION UI = "Panel_sec_nt37801_120hz_wqhd_plus_dsc_vid.xml"
    SECTION RAW = RawFiles/Panel_sec_nt37801_120hz_wqhd_plus_dsc_vid.xml
}


FILE FREEFORM = B401799A-252E-481B-A610-B018D7271798 {
    SECTION UI = "Panel_zte_bf237_rm692h5_6p8_dev0_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_bf237_rm692h5_6p8_dev0_dsc_cmd.xml
}


FILE FREEFORM = 53E924FA-E6FE-4A28-8147-B55D45D14B18 {
    SECTION UI = "Panel_zte_bf237_rm692h5_6p8_dev1_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_bf237_rm692h5_6p8_dev1_dsc_cmd.xml
}


FILE FREEFORM = B028B72F-FBAC-4AC1-AF3F-C35AEFADB1C6 {
    SECTION UI = "Panel_zte_bf288_rm692h5_6p85_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_bf288_rm692h5_6p85_dsc_cmd.xml
}


FILE FREEFORM = 17E2CC39-4EB7-49BF-BA22-CC03B25E1407 {
    SECTION UI = "Panel_zte_bf289_rm692h5_sec_422p_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_bf289_rm692h5_sec_422p_cmd.xml
}


FILE FREEFORM = 6670DDB4-45AC-4FFA-99B6-FB31F3F56374 {
    SECTION UI = "Panel_zte_himax_hx8874_12p3_dev0_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_himax_hx8874_12p3_dev0_dsc_cmd.xml
}


FILE FREEFORM = 13FAA8F7-0D17-4618-9738-F8BD45D6A3E9 {
    SECTION UI = "Panel_zte_himax_hx8874_12p3_dev1_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_himax_hx8874_12p3_dev1_dsc_cmd.xml
}


FILE FREEFORM = 1CBC8574-3DDD-400E-927B-4D00DA731022 {
    SECTION UI = "Panel_zte_himax_hx8874_9p06_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_himax_hx8874_9p06_dsc_cmd.xml
}


FILE FREEFORM = DC7223EC-E62C-42C5-AE8C-315C60C55DA3 {
    SECTION UI = "Panel_zte_bf368_nt37900b_8p03_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_bf368_nt37900b_8p03_dsc_cmd.xml
}


FILE FREEFORM = DC6FF0C3-8102-4F9F-AE81-F431745DE254 {
    SECTION UI = "Panel_zte_bf369_rm692k0_6p534_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_bf369_rm692k0_6p534_dsc_cmd.xml
}


FILE FREEFORM = E3ABC1CD-82DB-46BD-BA8E-FB97EB6DC01C {
    SECTION UI = "Panel_zte_hehui_rm692h5_6p02_dev0_dsc_cmd.xml"
    SECTION RAW = RawFiles/Panel_zte_hehui_rm692h5_6p02_dev0_dsc_cmd.xml
}


FILE FREEFORM = E4E05D69-1B86-4FF1-AAB4-F6C570CE0870 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_spr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_spr.xml
}


FILE FREEFORM = 61D46807-762F-48D8-A4F0-147BFF0F4084 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura_nspr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_cmd_demura_nspr.xml
}


FILE FREEFORM = 359CB564-3576-4B6B-AB0C-6389B47ECF08 {
    SECTION UI = "Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura_nspr.xml"
    SECTION RAW = RawFiles/Panel_nt37801_120hz_wqhd_plus_dsc_vid_demura_nspr.xml
}


FILE FREEFORM = 2556DAE8-93E4-4FDF-B00C-1D9B3ECBD0C1 {
    SECTION UI = "Panel_sec_vtdr6130_144hz_fhd_plus_dsc_vid_rfi.xml"
    SECTION RAW = RawFiles/Panel_sec_vtdr6130_144hz_fhd_plus_dsc_vid_rfi.xml
}


FILE FREEFORM = B037099A-8076-4240-869F-3C3FA45F22BD {
    SECTION UI = "Panel_sec_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml"
    SECTION RAW = RawFiles/Panel_sec_vtdr6130_144hz_fhd_plus_dsc_cmd_rfi.xml
}


FILE FREEFORM = 03E9256F-E621-48D8-8576-7E3B4FCF2D41 {
    SECTION UI = "PanelSimConfig.csv"
    SECTION RAW = RawFiles/PanelSimConfig.csv
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}

INF QcomPkg/Application/Ebl/Ebl.inf